name: Docker Image CI

on:
  push
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Installing CLI-beta for OIDC
      run: |
              python3 -m pip install -q --upgrade pip
              pip install azure-cli
    - name: 'Run curl for token before default'
      run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          output=$(curl -vs -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | base64 -w0)
          echo $output
    - name: Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
    - name: login to ACR
      id: login-to-acr
      run: |
          TOKEN=$(az acr login --name wagnerregistry.azurecr.io --expose-token --output tsv --query accessToken)
          docker login wagnerregistry.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $TOKEN
    - name: pull and push alpine
      run: |
         docker pull alpine
         docker tag alpine wagnerregistry.azurecr.io/handsome/alpine:latest
         docker push wagnerregistry.azurecr.io/other-repo/alpine
    - name: 'Run az commands'
      run: |
          az account show
          az group list
          pwd 
